// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIKeUZYthitM8HxTmcDuPw2WfBpo3iqDs',
    appId: '1:50479627374:web:7c51054d306846f07cba7f',
    messagingSenderId: '50479627374',
    projectId: 'flutter-chat-app-6af88',
    authDomain: 'flutter-chat-app-6af88.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6af88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg1wMrJSGly75NnpC2YlDpjdPeppt1Kpw',
    appId: '1:50479627374:android:799dec7cf8dd96737cba7f',
    messagingSenderId: '50479627374',
    projectId: 'flutter-chat-app-6af88',
    storageBucket: 'flutter-chat-app-6af88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVKLWOThb0pDWoLnjmu2eIlMPsr33-87A',
    appId: '1:50479627374:ios:7f508f33638a445a7cba7f',
    messagingSenderId: '50479627374',
    projectId: 'flutter-chat-app-6af88',
    storageBucket: 'flutter-chat-app-6af88.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVKLWOThb0pDWoLnjmu2eIlMPsr33-87A',
    appId: '1:50479627374:ios:9d68f6f32da311d27cba7f',
    messagingSenderId: '50479627374',
    projectId: 'flutter-chat-app-6af88',
    storageBucket: 'flutter-chat-app-6af88.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
